base/minimal-notebook/Dockerfile.cuda80
notebooks/cntk-notebook/Dockerfile
notebooks/cntk-notebook/Dockerfile.gpu
notebooks/mxnet-notebook/Dockerfile
notebooks/pytorch-notebook/Dockerfile
notebooks/pytorch-notebook/Dockerfile.gpu

move file
add cuda 9.0 dockerfile
remove switching user in mxnet notebook
format pytorch notebook
add cuda90 in pytorch notebook

add cntk notebook

---

env/caffe2/Dockerfile
env/caffe2/Dockerfile.gpu

Support Caffe2

---

env/tensorflow-13/Dockerfile
env/tensorflow-13/Dockerfile.gpu
env/tensorflow-14/Dockerfile
env/tensorflow-14/Dockerfile.gpu
env/tensorflow-15/Dockerfile
env/tensorflow-15/Dockerfile.gpu
env/tensorflow-16/Dockerfile
env/tensorflow-16/Dockerfile.gpu

- Support h5py
- Install TensorFlow from pip instead of Anaconda

Support h5py

---

env/caffe2/Dockerfile.gpu
env/cntk/Dockerfile
env/cntk/Dockerfile.gpu

- CPU notebook caffe2 version: 0.8.0
- GPU notebook caffe2 version: 0.8.2

Update Caffe2 GPU notebook

---

env/tensorflow-17/Dockerfile
env/tensorflow-17/Dockerfile.gpu

- Add TensorFlow 1.7.0 CPU/GPU notebooks

Support TensorFlow 1.7.0

---

base/minimal-notebook/Dockerfile
env/tensorflow-13/Dockerfile
env/tensorflow-13/Dockerfile.gpu
env/tensorflow-14/Dockerfile
env/tensorflow-14/Dockerfile.gpu
env/tensorflow-15/Dockerfile
env/tensorflow-15/Dockerfile.gpu
env/tensorflow-16/Dockerfile
env/tensorflow-16/Dockerfile.gpu
env/tensorflow-17/Dockerfile
env/tensorflow-17/Dockerfile.gpu

Install h5py at minimal-notebook

---

base/minimal-notebook/Dockerfile

Installation `aiforge` in base image

ST-1789 ST-1768: Put aiforge binary in the environment images

---

env/pytorch-031/Dockerfile
env/pytorch-031/Dockerfile.gpu
env/pytorch-031/README.md
env/pytorch-040/Dockerfile
env/pytorch-040/Dockerfile.gpu
env/pytorch-040/README.md
env/pytorch/README.md

- Move pytorch to pytorch-031
- Add PyTorch v0.4.0 CPU/GPU notebooks
- Update PyTorch v0.3.1 README.md
- Add PyTorch v0.4.0 README.md

Support PyTorch v0.4.0

---

base/minimal-notebook/Dockerfile

fix the bug `Working Dir is /home/jovyan`

Change WORKDIR to /workspace

---

base/minimal-notebook/Dockerfile

https://linkernetworks.atlassian.net/browse/ST-1879
We need to install nbextension for extension.js

install nbextension for extension.js

---

env/tensorflow-17/Dockerfile
env/tensorflow-17/Dockerfile.gpu

https://pypi.org/project/tensorflow/#history

Upgrade TensorFlow to v1.7.1

---

base/base-notebook/Dockerfile
base/base-notebook/Dockerfile.py2
base/minimal-notebook/Dockerfile

- Update Conda to 4.5.1
- Change Conda channel when installing Caffe in data science notebook

Fix #39 Caffe

---

env/datascience/1.0/Dockerfile
env/datascience/1.0/Dockerfile-gpu

- Remove Caffe (太雷了 先暫時拿掉)
- Lock TensorFlow version
- install PyTorch from PyPI

Lock TensorFlow version and remove caffe (data science env)

---

env/caffe/1.0/Dockerfile
env/caffe/1.0/Dockerfile.gpu
env/caffe2/0.8/Dockerfile
env/caffe2/0.8/Dockerfile.gpu
env/chainer/3.5/Dockerfile
env/chainer/3.5/Dockerfile.gpu
env/cntk/2.5/Dockerfile
env/cntk/2.5/Dockerfile.gpu
env/datascience/1.0/Dockerfile
env/datascience/1.0/Dockerfile.gpu
env/mxnet/1.1/Dockerfile
env/mxnet/1.1/Dockerfile.gpu
env/pytorch/0.3.1/Dockerfile
env/pytorch/0.3.1/Dockerfile.gpu
env/pytorch/0.4.0/Dockerfile
env/pytorch/0.4.0/Dockerfile.gpu
env/tensorflow/1.3/Dockerfile
env/tensorflow/1.3/Dockerfile.gpu
env/tensorflow/1.4/Dockerfile
env/tensorflow/1.4/Dockerfile.gpu
env/tensorflow/1.5.1/Dockerfile
env/tensorflow/1.5.1/Dockerfile.gpu
env/tensorflow/1.6/Dockerfile
env/tensorflow/1.6/Dockerfile.gpu
env/tensorflow/1.7/Dockerfile
env/tensorflow/1.7/Dockerfile.gpu
env/tensorflow/1.8/Dockerfile
env/tensorflow/1.8/Dockerfile.gpu

- add build arg SUBMIT_TOOL_NAME for trainer images

ST-1931, ST-1935: Rename submit tool

---

base/base-notebook/Dockerfile
base/base-notebook/start.sh

**Problem:**
- Jupyter default user is jovyan and cannot switch to root
**Solution:**
- Force use root to launch jupyter and enable sudo
**Side Effect:**
- Jupyter user got the root privilege

Fix #49 ST-1913 Force use root in jupyter

---

env/caffe/1.0/Dockerfile
env/caffe/1.0/Dockerfile.gpu
env/caffe2/0.8/Dockerfile
env/caffe2/0.8/Dockerfile.gpu
env/chainer/3.5/Dockerfile
env/chainer/3.5/Dockerfile.gpu
env/cntk/2.5/Dockerfile
env/cntk/2.5/Dockerfile.gpu
env/datascience/1.0/Dockerfile
env/datascience/1.0/Dockerfile.gpu
env/mxnet/1.1/Dockerfile
env/mxnet/1.1/Dockerfile.gpu
env/pytorch/0.3.1/Dockerfile
env/pytorch/0.3.1/Dockerfile.gpu
env/pytorch/0.4.0/Dockerfile
env/pytorch/0.4.0/Dockerfile.gpu
env/tensorflow/1.3/Dockerfile
env/tensorflow/1.3/Dockerfile.gpu
env/tensorflow/1.4/Dockerfile
env/tensorflow/1.4/Dockerfile.gpu
env/tensorflow/1.5.1/Dockerfile
env/tensorflow/1.5.1/Dockerfile.gpu
env/tensorflow/1.6/Dockerfile
env/tensorflow/1.6/Dockerfile.gpu
env/tensorflow/1.7/Dockerfile
env/tensorflow/1.7/Dockerfile.gpu
env/tensorflow/1.8/Dockerfile
env/tensorflow/1.8/Dockerfile.gpu

Only rename file when it's not `aurora`

Avoid move file error

---

env/caffe2/0.8/Dockerfile

**Problem:**
Original repo has been removed 
Issue pytorch/pytorch#7793
Related PR in master pytorch/pytorch#7581
**Solution:**
- Set to master first, until they make new tag.
**Side Effect:**
- Minor

Fix #53 fix pytorch 0.4.0

---

Makefile

**Problem:**
Current docker image name  `caffe2-0.8:0.8` 
**Solution:**
It should be `caffe2:0.8`
**Side Effect:**
- None

ST-1913: Fix wrong image target name

---

Makefile
env/caffe2/0.8/Dockerfile.gpu

**Problem:**
Caffe2 CPU build fixed, but lost on GPU part
**Solution:**
Migrate fix from CPU part

Fix caffe2 gpu build

---

Makefile

**Problem:**
- Push image logic changes cause base-image push failure.
**Solution:**
- Separate push image for base and env because they have different logic
**Side Effect:**
- None

Fix base image push failure cause push change specific for notebook

---

env/caffe/1.0/Dockerfile
env/caffe/1.0/Dockerfile.gpu

Related Issues:
- https://github.com/BVLC/caffe/issues/2677
- https://github.com/BVLC/caffe/issues/591
- https://github.com/BVLC/caffe/issues/5568

FIX: Add pyqt to the dependency list to fix caffe segmentation fault

---

env/caffe2/0.8/Dockerfile
env/caffe2/0.8/Dockerfile.gpu

Fix Caffe2

---

env/caffe/1.0/Dockerfile
env/caffe/1.0/Dockerfile.gpu

- 沒有 pydot 的話 make pytest 不會過
- 沒有 lmdb 的話 caffe example 跑不起來

Install pydot and lmdb in Caffe

---

env/caffe-ssd/1.0/Dockerfile
env/caffe-ssd/1.0/Dockerfile.gpu
env/caffe-ssd/1.0/jupyter_notebook_config.py
env/caffe-ssd/1.0/start-notebook.sh
env/caffe-ssd/1.0/start.sh
env/caffe-ssd/README.md

https://github.com/weiliu89/caffe/tree/ssd
https://hub.docker.com/r/fstyle/caffe-ssd

Support Caffe SSD

---

env/caffe-ssd/1.0/Dockerfile
env/caffe-ssd/1.0/Dockerfile.gpu

- pip install opencv-contrib-python

ST-2453 Support OpenCV in Caffe SSD environment

---

base/base-notebook/Dockerfile
base/base-notebook/Dockerfile.py2
env/caffe-ssd/1.0/Dockerfile
env/caffe-ssd/1.0/Dockerfile.gpu
env/caffe/1.0/Dockerfile
env/caffe/1.0/Dockerfile.gpu
env/pytorch/0.4.1/Dockerfile
env/pytorch/0.4.1/Dockerfile.gpu

- Rename jovyan to aurora
- Add group aurora with gid 2000 
- Add user aurora to group aurora
- Add group aurora to sudoers

ST-2467 Modify user and group for all environments
